[package]
name = "example"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
worker = "0.0.9"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
